#!/bin/bash

if [ ! -d $SECONDO_WORK_DIR/sgui ]; then
	echo "$SECONDO_WORK_DIR/sgui not found, check your SECONDO installation"
	exit -1
fi

guijar="$SECONDO_BUILD_DIR/bin/javagui/Javagui.jar"

if [ ! -f $guijar ]; then
	echo "$guijar not found, check your SECONDO installation"
	exit -1
fi

cd $SECONDO_WORK_DIR/sgui
java -Xmx80M -jar $guijar $*
